--[[
Yin Yang / Spotify catalog
==========================

This file is the single source of truth for Spotify tracks.

Each entry must provide:
- Name
- Artist
- Duration
- Cover
- AudioURL
- CacheName
]]

return {
    Catalog = {
        {
            Name = "House of Balloons",
            Artist = "The Weeknd",
            Duration = "3:30",
            Cover = "rbxassetid://71223149192706",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/The%20Weeknd%20-%20House%20of%20Balloons%20%20Sub.Espa%C3%B1ol%20%20Lyrics.mp3",
            CacheName = "house_of_balloons.mp3",
        },
        {
            Name = "MONTAGEM DESCE",
            Artist = "OTVphonk Y ZERTAL",
            Duration = "1:44",
            Cover = "rbxassetid://110140684521717",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/MONTAGEM%20DESCE%20-%20Super%20Slowed.mp3",
            CacheName = "montagem_desce_super_slowed.mp3",
        },
        {
            Name = "Die For You",
            Artist = "The Weeknd",
            Duration = "4:40",
            Cover = "rbxassetid://133558723550605",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/The%20Weeknd%20-%20Die%20For%20You.mp3",
            CacheName = "die_for_you_the_weeknd.mp3",
        },
        {
            Name = "MONTAGEM LIMERENCIA",
            Artist = "Oto8 & HXVSAGE",
            Duration = "1:48",
            Cover = "rbxassetid://95310569926046",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/Montagem%20Limerencia%20(Slowed)%20(1).mp3",
            CacheName = "montagem_limerencia_slowed_1.mp3",
        },
        {
            Name = "PIXY Legacy",
            Artist = "PIXY",
            Duration = "02:41",
            Cover = "rbxassetid://118599518159038",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/PIXY%20-%20LEGACY%20(Slowed%20down).mp3",
            CacheName = "pixy_legacy_slowed_down.mp3",
        },
        {
            Name = "My Kind Of Woman",
            Artist = "Mac DeMarco",
            Duration = "03:17",
            Cover = "rbxassetid://90323899389024",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Mac%20DeMarco%20%20My%20Kind%20Of%20Woman.mp3",
            CacheName = "my_kind_of_woman.mp3",
        },
        {
            Name = "Nuts",
            Artist = "Lil Peep ft. rainy bear",
            Duration = "01:25",
            Cover = "rbxassetid://84531015432547",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Lil%20Peep%20-%20nuts%20(feat.%20rainy%20bear)%20(Official%20Audio).mp3",
            CacheName = "nuts_feat_rainy_bear.mp3",
        },
        {
            Name = "One Of The Girls",
            Artist = "The Weeknd, JENNIE, Lily-Rose Depp",
            Duration = "04:18",
            Cover = "rbxassetid://108862102017007",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/The%20Weeknd%2C%20JENNIE%2C%20Lily-Rose%20Depp%20-%20One%20Of%20The%20Girls%20(Official%20Video).mp3",
            CacheName = "one_of_the_girls.mp3",
        },
        {
            Name = "Die For You",
            Artist = "Joji",
            Duration = "3:31",
            Cover = "rbxassetid://133558723550605",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Joji%20-%20Die%20For%20You.mp3",
            CacheName = "die_for_you_joji.mp3",
        },
        {
            Name = "NEW MAGIC WAND",
            Artist = "Tyler, The Creator",
            Duration = "3:15",
            Cover = "rbxassetid://115193336733347",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Tyler%2C%20The%20Creator%20-%20NEW%20MAGIC%20WAND%20%5Bespa%C3%B1ol%20%20lyrics%5D.mp3",
            CacheName = "new_magic_wand_espanol_lyrics.mp3",
        },
        {
            Name = "Addiction",
            Artist = "Lodown",
            Duration = "3:53",
            Cover = "rbxassetid://112678746759157",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/addiction%20(Slowed).mp3",
            CacheName = "addiction_slowed.mp3",
        },
        {
            Name = "Yala",
            Artist = "YALA",
            Duration = "2:39",
            Cover = "rbxassetid://97873295754017",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/YALA%20(Slowed).mp3",
            CacheName = "yala_slowed.mp3",
        },
        {
            Name = "Deja Vu",
            Artist = "33 nimb • y • CACAU",
            Duration = "1:42",
            Cover = "rbxassetid://109854752313229",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/deja%20vu%20-%2033nimb%2C%20CACAU%20CHUU.mp3",
            CacheName = "deja_vu_33nimb_cacau_chuu.mp3",
        },
        {
            Name = "Instrumental L.E.S",
            Artist = "gtuxvibes",
            Duration = "4:20",
            Cover = "rbxassetid://78670680459430",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Childish%20Gambino%20-%20L.E.S.%20instrumental%20%20best%20part%20%20slowed%20reverb.mp3",
            CacheName = "childish_gambino_les_instrumental_best_part_slowed_reverb.mp3",
        },
        {
            Name = "Sombra Estelar 1.0",
            Artist = "Ikeraus",
            Duration = "1:28",
            Cover = "rbxassetid://99878223372697",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Montagem%20sombra%20estelar%201.0.mp3",
            CacheName = "montagem_sombra_estelar_1_0.mp3",
        },
        {
            Name = "Worry (Slowed)",
            Artist = "lonown",
            Duration = "4:15",
            Cover = "rbxassetid://83428533770570",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/worry%20(ultra%20slowed).mp3",
            CacheName = "worry_ultra_slowed.mp3",
        },
        {
            Name = "VOZES INDICADOR",
            Artist = "heapper",
            Duration = "2:02",
            Cover = "rbxassetid://79593664773385",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/MONTAGEM%20VOZES%20INDICADOR%20(Ultra%20Slowed).mp3",
            CacheName = "montagem_vozes_indicador_ultra_slowed.mp3",
        },
        {
            Name = "stray.wav",
            Artist = "kurate music",
            Duration = "2:08",
            Cover = "rbxassetid://135619504487285",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Stray.wav%20-%20%24uNDOWN%20(slowed%20%20reverb).mp3",
            CacheName = "stray_wav_undown_slowed_reverb.mp3",
        },
        {
            Name = "Missing Textures",
            Artist = "NIVEK FFORHS",
            Duration = "3:10",
            Cover = "rbxassetid://101765267829842",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Missing%20Textures%20(Slowed%20Down).mp3",
            CacheName = "missing_textures_slowed_down.mp3",
        },
        {
            Name = "Starly Sloweb",
            Artist = "Lonown",
            Duration = "2:53",
            Cover = "rbxassetid://108323126145343",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/starly%20(Slowed).mp3",
            CacheName = "starly_slowed.mp3",
        },
        {
            Name = "VEM PERE REKA",
            Artist = "ns",
            Duration = "2:07",
            Cover = "rbxassetid://79615562047730",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/VEM%20PERE%20REKA%20-%20SLOWED%20-%20DJ%20KINN.mp3",
            CacheName = "vem_pere_reka_slowed_dj_kinn.mp3",
        },
        {
            Name = "ACIDO III (Over Slowed)",
            Artist = "thegoodvibeMusic",
            Duration = "5:08",
            Cover = "rbxassetid://99519775044720",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/ACIDO%20III%20(Over%20Slowed).mp3",
            CacheName = "acido_iii_over_slowed.mp3",
        },
        {
            Name = "HAZA (Alt Ver, Super Slowed)",
            Artist = "UdieNnx",
            Duration = "1:42",
            Cover = "rbxassetid://119528803652274",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/HAZA%20(Alt%20Ver%2C%20Super%20Slowed).mp3",
            CacheName = "haza_alt_ver_super_slowed.mp3",
        },
        {
            Name = "Les",
            Artist = "Donald Glover",
            Duration = "5:18",
            Cover = "rbxassetid://139788856067054",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/Les.mp3",
            CacheName = "les_donald_glover.mp3",
        },
        {
            Name = "MONTAGEM RUGADA",
            Artist = "cape.69",
            Duration = "1:32",
            Cover = "rbxassetid://119435648178938",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/MONTAGEM%20RUGADA.mp3",
            CacheName = "montagem_rugada.mp3",
        },
        {
            Name = "MONTAGEM SANTA FE 2",
            Artist = "Phonkero_OF",
            Duration = "2:18",
            Cover = "rbxassetid://98306863050969",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/MONTAGEM%20SANTA%20FE%202%20-%20QARAQSHY%20-%20(Super%20Slowed%20%26%20Reverb)%20-%20(Tiktok%20Version).mp3",
            CacheName = "montagem_santa_fe_2_super_slowed.mp3",
        },
        {
            Name = "TOMA PIPOCADA (Slowed)",
            Artist = "SilentEditz4k",
            Duration = "1:02",
            Cover = "rbxassetid://85312411427625",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/TOMA%20PIPOCADA%20-%20(%20Slowed%20)%20-%20DJ%20TLS%20DA%20ZL.mp3",
            CacheName = "toma_pipocada_slowed.mp3",
        },
        {
            Name = "VEM BOQUETANDO",
            Artist = "Phonk001-2k",
            Duration = "1:00",
            Cover = "rbxassetid://76821401143277",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/VEM%20BOQUETANDO%20-%20SO%20SOCADA%20BRUTA.mp3",
            CacheName = "vem_boquetando_so_socada_bruta.mp3",
        },
        {
            Name = "envy",
            Artist = "slxughter",
            Duration = "1:56",
            Cover = "rbxassetid://139864955210978",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/envy.mp3",
            CacheName = "envy_slxughter.mp3",
        },
        {
            Name = "montagem tudao (super slowed)",
            Artist = "Darkkeraunos",
            Duration = "1:26",
            Cover = "rbxassetid://95842529567291",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/montagem%20tudao%20-%20(%20super%20slowed%20).mp3",
            CacheName = "montagem_tudao_super_slowed.mp3",
        },
        {
            Name = "𝐓𝐔𝐑𝐀𝐍(𝐒𝐋𝐎𝐖𝐄𝐃) – Remade",
            Artist = "kr5rect",
            Duration = "1:26",
            Cover = "rbxassetid://117960059356869",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/%F0%9D%90%93%F0%9D%90%94%F0%9D%90%91%F0%9D%90%80%F0%9D%90%8D(%F0%9D%90%92%F0%9D%90%8B%F0%9D%90%8E%F0%9D%90%96%F0%9D%90%84%F0%9D%90%83)%20%20%F0%9D%90%91%F0%9D%90%9E%F0%9D%90%A6%F0%9D%90%9A%F0%9D%90%9D%F0%9D%90%9E.mp3",
            CacheName = "turan_slowed_remade.mp3",
        },
        {
            Name = "Love Me Not (Slowed + Reverb)",
            Artist = "Ravyn Lenae",
            Duration = "04:47",
            Cover = "rbxassetid://71057643767851",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/ravynlenae-lovemenot%5Bslowedreverb%5D.mp3",
            CacheName = "love_me_not_slowed_reverb.mp3",
        },
        {
            Name = "No One Noticed (Extended English)",
            Artist = "The Marías",
            Duration = "04:45",
            Cover = "rbxassetid://126630425236730",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/NoOneNoticed%28ExtendedEnglish%29.mp3",
            CacheName = "no_one_noticed_extended_english.mp3",
        },
        {
            Name = "Goth (Slowed + Reverb)",
            Artist = "Sidewalks and Skeletons",
            Duration = "04:13",
            Cover = "rbxassetid://125085283831526",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Goth%28SlowedReverb%29.mp3",
            CacheName = "goth_slowed_reverb.mp3",
        },
        {
            Name = "505",
            Artist = "Arctic Monkeys",
            Duration = "04:19",
            Cover = "rbxassetid://130474089189523",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/505-ARCTICMONKEYSComeRideWithMeHondaCBR500NightRide.mp3",
            CacheName = "505_arctic_monkeys.mp3",
        },
        {
            Name = "LET THE WORLD BURN",
            Artist = "Chris Grey",
            Duration = "02:43",
            Cover = "rbxassetid://75341028120055",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/ChrisGrey-LETTHEWORLDBURN%28OfficialLyricVideo%29.mp3",
            CacheName = "let_the_world_burn_chris_grey.mp3",
        },
        {
            Name = "Babydoll",
            Artist = "Dominic Fike",
            Duration = "02:34",
            Cover = "rbxassetid://108941742632203",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Babydoll.mp3",
            CacheName = "babydoll_dominic_fike.mp3",
        },
        {
            Name = "The Boy Is Mine",
            Artist = "Brandy & Monica",
            Duration = "04:02",
            Cover = "rbxassetid://138208744721983",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Brandy%26Monica-TheBoyIsMine%28OfficialVideo%29.mp3",
            CacheName = "the_boy_is_mine_brandy_monica.mp3",
        },
        {
            Name = "Shut up My Moms Calling",
            Artist = "Hotel Ugly",
            Duration = "02:45",
            Cover = "rbxassetid://115961637547179",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/ShutupMyMomsCalling.mp3",
            CacheName = "shut_up_my_moms_calling.mp3",
        },
        {
            Name = "Sometimes",
            Artist = "Mattyeux & Princess Chelsea",
            Duration = "03:28",
            Cover = "rbxassetid://130594219203923",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Mattyeux%2CPrincessChelsea-Sometimes%28OfficialMusicVideo%29.mp3",
            CacheName = "sometimes_mattyeux_princess_chelsea.mp3",
        },
        {
            Name = "headlock x headlock",
            Artist = "senjxn",
            Duration = "03:42",
            Cover = "rbxassetid://76144835746169",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/headlockxheadlock.mp3",
            CacheName = "headlock_x_headlock_senjxn.mp3",
        },
        {
            Name = "Diamonds & Pearls (Slowed to Perfection)",
            Artist = "QKReign, VaporGod",
            Duration = "03:25",
            Cover = "rbxassetid://105897309192629",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/QKReign%20%2C%20VaporGod%20-%20Diamonds%20%26%20Pearls%20(slowed%20to%20perfection).mp3",
            CacheName = "qkreign_vaporgod_diamonds_pearls_slowed.mp3",
        },
        {
            Name = "Обнял, поцеловал X Tuesday - Slowed",
            Artist = "ForceTx",
            Duration = "02:56",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/ForceTx%20-%20Obnyal%20Potseloval%20X%20Tuesday%20%28Slowed%29.mp3",
            CacheName = "forcetx_obnyal_potseloval_x_tuesday_slowed.mp3",
        },
        {
            Name = "MALVADO DE VAPO",
            Artist = "xccvdxz, Y3LLAVISION",
            Duration = "01:17",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/xccvdxz%2C%20Y3LLAVISION%20-%20MALVADO%20DE%20VAPO.mp3",
            CacheName = "xccvdxz_y3llavision_malvado_de_vapo.mp3",
        },
        {
            Name = "• Chérie • 23 • (Sloweddd)",
            Artist = "VDYCD",
            Duration = "03:44",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/VDYCD%20-%20Cherie%2023%20%28Sloweddd%29.mp3",
            CacheName = "vdycd_cherie_23_sloweddd.mp3",
        },
        {
            Name = "MONTAGEM PENSAR - Ultra Slowed",
            Artist = "Phonknight",
            Duration = "02:04",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Phonknight%20-%20MONTAGEM%20PENSAR%20%28Ultra%20Slowed%29.mp3",
            CacheName = "phonknight_montagem_pensar_ultra_slowed.mp3",
        },
    },
}
