--[[
Yin Yang / Spotify catalog
==========================

This file is the single source of truth for Spotify tracks.

Each entry must provide:
- Name
- Artist
- Duration
- Cover
- AudioURL
- CacheName
]]

return {
    Catalog = {
        {
            Name = "House of Balloons",
            Artist = "The Weeknd",
            Duration = "3:30",
            Cover = "rbxassetid://71223149192706",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/The%20Weeknd%20-%20House%20of%20Balloons%20%20Sub.Espa%C3%B1ol%20%20Lyrics.mp3",
            CacheName = "house_of_balloons.mp3",
        },
        {
            Name = "MONTAGEM DESCE",
            Artist = "OTVphonk Y ZERTAL",
            Duration = "1:44",
            Cover = "rbxassetid://110140684521717",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/MONTAGEM%20DESCE%20-%20Super%20Slowed.mp3",
            CacheName = "montagem_desce_super_slowed.mp3",
        },
        {
            Name = "Die For You",
            Artist = "The Weeknd",
            Duration = "4:40",
            Cover = "rbxassetid://133558723550605",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/The%20Weeknd%20-%20Die%20For%20You.mp3",
            CacheName = "die_for_you_the_weeknd.mp3",
        },
        {
            Name = "MONTAGEM LIMERENCIA",
            Artist = "Oto8 & HXVSAGE",
            Duration = "1:48",
            Cover = "rbxassetid://95310569926046",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/Montagem%20Limerencia%20(Slowed)%20(1).mp3",
            CacheName = "montagem_limerencia_slowed_1.mp3",
        },
        {
            Name = "PIXY Legacy",
            Artist = "PIXY",
            Duration = "02:41",
            Cover = "rbxassetid://118599518159038",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/PIXY%20-%20LEGACY%20(Slowed%20down).mp3",
            CacheName = "pixy_legacy_slowed_down.mp3",
        },
        {
            Name = "My Kind Of Woman",
            Artist = "Mac DeMarco",
            Duration = "03:17",
            Cover = "rbxassetid://90323899389024",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Mac%20DeMarco%20%20My%20Kind%20Of%20Woman.mp3",
            CacheName = "my_kind_of_woman.mp3",
        },
        {
            Name = "Nuts",
            Artist = "Lil Peep ft. rainy bear",
            Duration = "01:25",
            Cover = "rbxassetid://84531015432547",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Lil%20Peep%20-%20nuts%20(feat.%20rainy%20bear)%20(Official%20Audio).mp3",
            CacheName = "nuts_feat_rainy_bear.mp3",
        },
        {
            Name = "One Of The Girls",
            Artist = "The Weeknd, JENNIE, Lily-Rose Depp",
            Duration = "04:18",
            Cover = "rbxassetid://108862102017007",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/The%20Weeknd%2C%20JENNIE%2C%20Lily-Rose%20Depp%20-%20One%20Of%20The%20Girls%20(Official%20Video).mp3",
            CacheName = "one_of_the_girls.mp3",
        },
        {
            Name = "Die For You",
            Artist = "Joji",
            Duration = "3:31",
            Cover = "rbxassetid://133558723550605",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Joji%20-%20Die%20For%20You.mp3",
            CacheName = "die_for_you_joji.mp3",
        },
        {
            Name = "NEW MAGIC WAND",
            Artist = "Tyler, The Creator",
            Duration = "3:15",
            Cover = "rbxassetid://115193336733347",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/Tyler%2C%20The%20Creator%20-%20NEW%20MAGIC%20WAND%20%5Bespa%C3%B1ol%20%20lyrics%5D.mp3",
            CacheName = "new_magic_wand_espanol_lyrics.mp3",
        },
        {
            Name = "Addiction",
            Artist = "Lodown",
            Duration = "3:53",
            Cover = "rbxassetid://112678746759157",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/addiction%20(Slowed).mp3",
            CacheName = "addiction_slowed.mp3",
        },
        {
            Name = "Yala",
            Artist = "YALA",
            Duration = "2:39",
            Cover = "rbxassetid://97873295754017",
            AudioURL = "https://raw.githubusercontent.com/Yinyangzx/Yin-ControllerMusic/main/YALA%20(Slowed).mp3",
            CacheName = "yala_slowed.mp3",
        },
        {
            Name = "Deja Vu",
            Artist = "33 nimb • y • CACAU",
            Duration = "1:42",
            Cover = "rbxassetid://109854752313229",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A/main/deja%20vu%20-%2033nimb%2C%20CACAU%20CHUU.mp3",
            CacheName = "deja_vu_33nimb_cacau_chuu.mp3",
        },
        {
            Name = "Instrumental L.E.S",
            Artist = "gtuxvibes",
            Duration = "4:20",
            Cover = "rbxassetid://78670680459430",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Childish%20Gambino%20-%20L.E.S.%20instrumental%20%20best%20part%20%20slowed%20reverb.mp3",
            CacheName = "childish_gambino_les_instrumental_best_part_slowed_reverb.mp3",
        },
        {
            Name = "Sombra Estelar 1.0",
            Artist = "Ikeraus",
            Duration = "1:28",
            Cover = "rbxassetid://99878223372697",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Montagem%20sombra%20estelar%201.0.mp3",
            CacheName = "montagem_sombra_estelar_1_0.mp3",
        },
        {
            Name = "Worry (Slowed)",
            Artist = "lonown",
            Duration = "4:15",
            Cover = "rbxassetid://83428533770570",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/worry%20(ultra%20slowed).mp3",
            CacheName = "worry_ultra_slowed.mp3",
        },
        {
            Name = "VOZES INDICADOR",
            Artist = "heapper",
            Duration = "2:02",
            Cover = "rbxassetid://79593664773385",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/MONTAGEM%20VOZES%20INDICADOR%20(Ultra%20Slowed).mp3",
            CacheName = "montagem_vozes_indicador_ultra_slowed.mp3",
        },
        {
            Name = "stray.wav",
            Artist = "kurate music",
            Duration = "2:08",
            Cover = "rbxassetid://135619504487285",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Stray.wav%20-%20%24uNDOWN%20(slowed%20%20reverb).mp3",
            CacheName = "stray_wav_undown_slowed_reverb.mp3",
        },
        {
            Name = "Missing Textures",
            Artist = "NIVEK FFORHS",
            Duration = "3:10",
            Cover = "rbxassetid://101765267829842",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/Missing%20Textures%20(Slowed%20Down).mp3",
            CacheName = "missing_textures_slowed_down.mp3",
        },
        {
            Name = "Starly Sloweb",
            Artist = "Lonown",
            Duration = "2:53",
            Cover = "rbxassetid://108323126145343",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/starly%20(Slowed).mp3",
            CacheName = "starly_slowed.mp3",
        },
        {
            Name = "VEM PERE REKA",
            Artist = "ns",
            Duration = "2:07",
            Cover = "rbxassetid://79615562047730",
            AudioURL = "https://raw.githubusercontent.com/nbritez6729-blip/A2/main/VEM%20PERE%20REKA%20-%20SLOWED%20-%20DJ%20KINN.mp3",
            CacheName = "vem_pere_reka_slowed_dj_kinn.mp3",
        },
        {
            Name = "ACIDO III (Over Slowed)",
            Artist = "thegoodvibeMusic",
            Duration = "5:08",
            Cover = "rbxassetid://99519775044720",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/ACIDO%20III%20(Over%20Slowed).mp3",
            CacheName = "acido_iii_over_slowed.mp3",
        },
        {
            Name = "HAZA (Alt Ver, Super Slowed)",
            Artist = "UdieNnx",
            Duration = "1:42",
            Cover = "rbxassetid://119528803652274",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/HAZA%20(Alt%20Ver%2C%20Super%20Slowed).mp3",
            CacheName = "haza_alt_ver_super_slowed.mp3",
        },
        {
            Name = "Les",
            Artist = "Donald Glover",
            Duration = "5:18",
            Cover = "rbxassetid://139788856067054",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/Les.mp3",
            CacheName = "les_donald_glover.mp3",
        },
        {
            Name = "MONTAGEM RUGADA",
            Artist = "cape.69",
            Duration = "1:32",
            Cover = "rbxassetid://119435648178938",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/MONTAGEM%20RUGADA.mp3",
            CacheName = "montagem_rugada.mp3",
        },
        {
            Name = "MONTAGEM SANTA FE 2",
            Artist = "Phonkero_OF",
            Duration = "2:18",
            Cover = "rbxassetid://98306863050969",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/MONTAGEM%20SANTA%20FE%202%20-%20QARAQSHY%20-%20(Super%20Slowed%20%26%20Reverb)%20-%20(Tiktok%20Version).mp3",
            CacheName = "montagem_santa_fe_2_super_slowed.mp3",
        },
        {
            Name = "TOMA PIPOCADA (Slowed)",
            Artist = "SilentEditz4k",
            Duration = "1:02",
            Cover = "rbxassetid://85312411427625",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/TOMA%20PIPOCADA%20-%20(%20Slowed%20)%20-%20DJ%20TLS%20DA%20ZL.mp3",
            CacheName = "toma_pipocada_slowed.mp3",
        },
        {
            Name = "VEM BOQUETANDO",
            Artist = "Phonk001-2k",
            Duration = "1:00",
            Cover = "rbxassetid://76821401143277",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/VEM%20BOQUETANDO%20-%20SO%20SOCADA%20BRUTA.mp3",
            CacheName = "vem_boquetando_so_socada_bruta.mp3",
        },
        {
            Name = "envy",
            Artist = "slxughter",
            Duration = "1:56",
            Cover = "rbxassetid://139864955210978",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/envy.mp3",
            CacheName = "envy_slxughter.mp3",
        },
        {
            Name = "montagem tudao (super slowed)",
            Artist = "Darkkeraunos",
            Duration = "1:26",
            Cover = "rbxassetid://95842529567291",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/montagem%20tudao%20-%20(%20super%20slowed%20).mp3",
            CacheName = "montagem_tudao_super_slowed.mp3",
        },
        {
            Name = "𝐓𝐔𝐑𝐀𝐍(𝐒𝐋𝐎𝐖𝐄𝐃) – Remade",
            Artist = "kr5rect",
            Duration = "1:26",
            Cover = "rbxassetid://117960059356869",
            AudioURL = "https://raw.githubusercontent.com/nzom404-png/Music/main/%F0%9D%90%93%F0%9D%90%94%F0%9D%90%91%F0%9D%90%80%F0%9D%90%8D(%F0%9D%90%92%F0%9D%90%8B%F0%9D%90%8E%F0%9D%90%96%F0%9D%90%84%F0%9D%90%83)%20%20%F0%9D%90%91%F0%9D%90%9E%F0%9D%90%A6%F0%9D%90%9A%F0%9D%90%9D%F0%9D%90%9E.mp3",
            CacheName = "turan_slowed_remade.mp3",
        },
        {
            Name = "Love Me Not (Slowed + Reverb)",
            Artist = "Ravyn Lenae",
            Duration = "04:47",
            Cover = "rbxassetid://71057643767851",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/ravynlenae-lovemenot%5Bslowedreverb%5D.mp3",
            CacheName = "love_me_not_slowed_reverb.mp3",
        },
        {
            Name = "No One Noticed (Extended English)",
            Artist = "The Marías",
            Duration = "04:45",
            Cover = "rbxassetid://126630425236730",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/NoOneNoticed%28ExtendedEnglish%29.mp3",
            CacheName = "no_one_noticed_extended_english.mp3",
        },
        {
            Name = "Goth (Slowed + Reverb)",
            Artist = "Sidewalks and Skeletons",
            Duration = "04:13",
            Cover = "rbxassetid://125085283831526",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Goth%28SlowedReverb%29.mp3",
            CacheName = "goth_slowed_reverb.mp3",
        },
        {
            Name = "505",
            Artist = "Arctic Monkeys",
            Duration = "04:19",
            Cover = "rbxassetid://130474089189523",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/505-ARCTICMONKEYSComeRideWithMeHondaCBR500NightRide.mp3",
            CacheName = "505_arctic_monkeys.mp3",
        },
        {
            Name = "LET THE WORLD BURN",
            Artist = "Chris Grey",
            Duration = "02:43",
            Cover = "rbxassetid://75341028120055",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/ChrisGrey-LETTHEWORLDBURN%28OfficialLyricVideo%29.mp3",
            CacheName = "let_the_world_burn_chris_grey.mp3",
        },
        {
            Name = "Babydoll",
            Artist = "Dominic Fike",
            Duration = "02:34",
            Cover = "rbxassetid://108941742632203",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Babydoll.mp3",
            CacheName = "babydoll_dominic_fike.mp3",
        },
        {
            Name = "The Boy Is Mine",
            Artist = "Brandy & Monica",
            Duration = "04:02",
            Cover = "rbxassetid://138208744721983",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Brandy%26Monica-TheBoyIsMine%28OfficialVideo%29.mp3",
            CacheName = "the_boy_is_mine_brandy_monica.mp3",
        },
        {
            Name = "Shut up My Moms Calling",
            Artist = "Hotel Ugly",
            Duration = "02:45",
            Cover = "rbxassetid://115961637547179",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/ShutupMyMomsCalling.mp3",
            CacheName = "shut_up_my_moms_calling.mp3",
        },
        {
            Name = "Sometimes",
            Artist = "Mattyeux & Princess Chelsea",
            Duration = "03:28",
            Cover = "rbxassetid://130594219203923",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/Mattyeux%2CPrincessChelsea-Sometimes%28OfficialMusicVideo%29.mp3",
            CacheName = "sometimes_mattyeux_princess_chelsea.mp3",
        },
        {
            Name = "headlock x headlock",
            Artist = "senjxn",
            Duration = "03:42",
            Cover = "rbxassetid://76144835746169",
            AudioURL = "https://raw.githubusercontent.com/nbritez911-sys/music/main/tracks/headlockxheadlock.mp3",
            CacheName = "headlock_x_headlock_senjxn.mp3",
        },
        {
            Name = "Diamonds & Pearls (Slowed to Perfection)",
            Artist = "QKReign, VaporGod",
            Duration = "03:25",
            Cover = "rbxassetid://105897309192629",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/QKReign%20%2C%20VaporGod%20-%20Diamonds%20%26%20Pearls%20(slowed%20to%20perfection).mp3",
            CacheName = "qkreign_vaporgod_diamonds_pearls_slowed.mp3",
        },
        {
            Name = "Обнял, поцеловал X Tuesday - Slowed",
            Artist = "ForceTx",
            Duration = "02:56",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/ForceTx%20-%20Obnyal%20Potseloval%20X%20Tuesday%20%28Slowed%29.mp3",
            CacheName = "forcetx_obnyal_potseloval_x_tuesday_slowed.mp3",
        },
        {
            Name = "MALVADO DE VAPO",
            Artist = "xccvdxz, Y3LLAVISION",
            Duration = "01:17",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/xccvdxz%2C%20Y3LLAVISION%20-%20MALVADO%20DE%20VAPO.mp3",
            CacheName = "xccvdxz_y3llavision_malvado_de_vapo.mp3",
        },
        {
            Name = "• Chérie • 23 • (Sloweddd)",
            Artist = "VDYCD",
            Duration = "03:44",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/VDYCD%20-%20Cherie%2023%20%28Sloweddd%29.mp3",
            CacheName = "vdycd_cherie_23_sloweddd.mp3",
        },
        {
            Name = "MONTAGEM PENSAR - Ultra Slowed",
            Artist = "Phonknight",
            Duration = "02:04",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Phonknight%20-%20MONTAGEM%20PENSAR%20%28Ultra%20Slowed%29.mp3",
            CacheName = "phonknight_montagem_pensar_ultra_slowed.mp3",
        },
        {
            Name = "AUTOMOTIVO DECORADA (Super Slowed)",
            Artist = "LXGHTXNG",
            Duration = "01:50",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/LXGHTXNG%20-%20AUTOMOTIVO%20DECORADA%20(Super%20Slowed).mp3",
            CacheName = "lxghtxng_automotivo_decorada_super_slowed.mp3",
        },
        {
            Name = "MONTAGEM URANIUM (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "02:14",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/MONTAGEM%20URANIUM%20(Slowed%20%2B%20Reverb).mp3",
            CacheName = "montagem_uranium_slowed_reverb.mp3",
        },
        {
            Name = "So Bitter (Slowed Best Part)",
            Artist = "Stxlkin",
            Duration = "01:25",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Stxlkin%20-%20So%20Bitter%20(Slowed%20Best%20Part).mp3",
            CacheName = "stxlkin_so_bitter_slowed_best_part.mp3",
        },
        {
            Name = "I Thought I Saw Your Face Today",
            Artist = "Artista no especificado",
            Duration = "02:50",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/I%20Thought%20I%20Saw%20Your%20Face%20Today.mp3",
            CacheName = "i_thought_i_saw_your_face_today.mp3",
        },
        {
            Name = "Infrunami",
            Artist = "Steve Lacy",
            Duration = "02:58",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Steve%20Lacy%20-%20Infrunami.mp3",
            CacheName = "steve_lacy_infrunami.mp3",
        },
        {
            Name = "Christmas Kids",
            Artist = "Roar",
            Duration = "02:16",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Roar%20-%20Christmas%20Kids.mp3",
            CacheName = "roar_christmas_kids.mp3",
        },
        {
            Name = "Tek It",
            Artist = "Cafuné",
            Duration = "03:12",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Cafun%C3%A9%20-%20Tek%20It.mp3",
            CacheName = "cafune_tek_it.mp3",
        },
        {
            Name = "Loving Machine",
            Artist = "TV Girl",
            Duration = "03:47",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/TV%20Girl%20-%20Loving%20Machine.mp3",
            CacheName = "tv_girl_loving_machine.mp3",
        },
        {
            Name = "Smells Like Teen Spirit",
            Artist = "Nirvana",
            Duration = "04:38",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Nirvana%20-%20Smells%20Like%20Teen%20Spirit.mp3",
            CacheName = "nirvana_smells_like_teen_spirit.mp3",
        },
        {
            Name = "M.",
            Artist = "Artista no especificado",
            Duration = "03:44",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/M..mp3",
            CacheName = "m_unknown.mp3",
        },
        {
            Name = "we fell in love in october",
            Artist = "girl in red",
            Duration = "03:07",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/girl%20in%20red%20-%20we%20fell%20in%20love%20in%20october.mp3",
            CacheName = "girl_in_red_we_fell_in_love_in_october.mp3",
        },
        {
            Name = "High Enough",
            Artist = "K.Flay",
            Duration = "03:49",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/K.Flay%20-%20High%20Enough.mp3",
            CacheName = "k_flay_high_enough.mp3",
        },
        {
            Name = "BIRDS OF A FEATHER",
            Artist = "Billie Eilish",
            Duration = "03:28",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Billie%20Eilish%20-%20BIRDS%20OF%20A%20FEATHER.mp3",
            CacheName = "billie_eilish_birds_of_a_feather.mp3",
        },
        {
            Name = "Obsessed (fvckar on audio, slowed + reverb)",
            Artist = "Mariah Carey",
            Duration = "04:40",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Mariah%20Carey%20-%20Obsessed%20(fvckar%20on%20audio%2C%20slowed%20%2B%20reverb).mp3",
            CacheName = "mariah_carey_obsessed_fvckar_slowed_reverb.mp3",
        },
        {
            Name = "under your spell (slowed + reverb)",
            Artist = "Snow Strippers",
            Duration = "04:16",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Snow%20Strippers%20-%20under%20your%20spell%20(slowed%20%2B%20reverb).mp3",
            CacheName = "snow_strippers_under_your_spell_slowed_reverb.mp3",
        },
        {
            Name = "Impostor Syndrome",
            Artist = "Sidney Gish",
            Duration = "04:54",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Sidney%20Gish%20-%20Impostor%20Syndrome.mp3",
            CacheName = "sidney_gish_impostor_syndrome.mp3",
        },
        {
            Name = "back to friends",
            Artist = "sombr",
            Duration = "03:22",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/sombr%20-%20back%20to%20friends.mp3",
            CacheName = "sombr_back_to_friends.mp3",
        },
        {
            Name = "Love Potions (slowed to perfection)",
            Artist = "BJ Lips",
            Duration = "03:03",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/BJ%20Lips%20-%20Love%20Potions%20(slowed%20to%20perfection).mp3",
            CacheName = "bj_lips_love_potions_slowed_to_perfection.mp3",
        },
        {
            Name = "Music To Watch Boys To (Demo)",
            Artist = "Lana Del Rey",
            Duration = "02:33",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Lana%20Del%20Rey%20-%20Music%20To%20Watch%20Boys%20To%20(Demo).mp3",
            CacheName = "lana_del_rey_music_to_watch_boys_to_demo.mp3",
        },
        {
            Name = "K. (AMV edit)",
            Artist = "Cigarettes After Sex",
            Duration = "04:47",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Cigarettes%20After%20Sex%20-%20K.%20(AMV%20edit).mp3",
            CacheName = "cigarettes_after_sex_k_amv_edit.mp3",
        },
        {
            Name = "Ojos Tristes",
            Artist = "Selena Gomez, benny blanco",
            Duration = "03:22",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Selena%20Gomez%2C%20benny%20blanco%20-%20Ojos%20Tristes.mp3",
            CacheName = "selena_gomez_benny_blanco_ojos_tristes.mp3",
        },
        {
            Name = "Dark Red",
            Artist = "Steve Lacy",
            Duration = "02:53",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Steve%20Lacy%20-%20Dark%20Red.mp3",
            CacheName = "steve_lacy_dark_red.mp3",
        },
        {
            Name = "Love Me",
            Artist = "JMSN",
            Duration = "04:29",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/JMSN%20-%20Love%20Me.mp3",
            CacheName = "jmsn_love_me.mp3",
        },
        {
            Name = "Brooklyn Baby",
            Artist = "Lana Del Rey",
            Duration = "05:53",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Lana%20Del%20Rey%20-%20Brooklyn%20Baby.mp3",
            CacheName = "lana_del_rey_brooklyn_baby.mp3",
        },
        {
            Name = "Ultraviolence",
            Artist = "Lana Del Rey",
            Duration = "04:23",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Lana%20Del%20Rey%20-%20Ultraviolence.mp3",
            CacheName = "lana_del_rey_ultraviolence.mp3",
        },
        {
            Name = "Summertime Sadness",
            Artist = "Lana Del Rey",
            Duration = "04:25",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/Lana%20Del%20Rey%20-%20Summertime%20Sadness.mp3",
            CacheName = "lana_del_rey_summertime_sadness.mp3",
        },
        {
            Name = "MONTAGEM DOMER (Super Slowed)",
            Artist = "Paizo, DJ LXILL, DJ FallThox",
            Duration = "1:27",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/paizo_djlxill_djfallthox_montagem_domer_super_slowed.mp3",
            CacheName = "paizo_djlxill_djfallthox_montagem_domer_super_slowed.mp3",
        },
        {
            Name = "MONTAGEM BANDIDO (Super Slowed)",
            Artist = "Artista no especificado",
            Duration = "1:50",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/montagem_bandido_super_slowed.mp3",
            CacheName = "montagem_bandido_super_slowed.mp3",
        },
        {
            Name = "Fendi 2",
            Artist = "Artista no especificado",
            Duration = "1:31",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/fendi_2.mp3",
            CacheName = "fendi_2.mp3",
        },
        {
            Name = "MANDE MANDE (Slowed)",
            Artist = "CHASHKA, KEFIRA",
            Duration = "1:41",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/chashka_kefira_mande_mande_slowed.mp3",
            CacheName = "chashka_kefira_mande_mande_slowed.mp3",
        },
        {
            Name = "CANTALALA (Slowed)",
            Artist = "Artista no especificado",
            Duration = "2:14",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/cantalala_slowed.mp3",
            CacheName = "cantalala_slowed.mp3",
        },
        {
            Name = "AVOID ME",
            Artist = "KUTE",
            Duration = "1:46",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/kute_avoid_me.mp3",
            CacheName = "kute_avoid_me.mp3",
        },
        {
            Name = "SPOOKY",
            Artist = "Artista no especificado",
            Duration = "1:37",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/spooky.mp3",
            CacheName = "spooky.mp3",
        },
        {
            Name = "YUM YUM",
            Artist = "Artista no especificado",
            Duration = "2:10",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/yum_yum.mp3",
            CacheName = "yum_yum.mp3",
        },
        {
            Name = "FUNK DO SURPRISE",
            Artist = "Artista no especificado",
            Duration = "1:12",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/funk_do_surprise.mp3",
            CacheName = "funk_do_surprise.mp3",
        },
        {
            Name = "VEM NO PIQUE (Ultra Slowed)",
            Artist = "Artista no especificado",
            Duration = "2:00",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/vem_no_pique_ultra_slowed.mp3",
            CacheName = "vem_no_pique_ultra_slowed.mp3",
        },
        {
            Name = "LUNA BALA (Slowed)",
            Artist = "Artista no especificado",
            Duration = "2:04",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/luna_bala_slowed.mp3",
            CacheName = "luna_bala_slowed.mp3",
        },
        {
            Name = "Nada Nada (Super Slowed)",
            Artist = "Artista no especificado",
            Duration = "1:53",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/nada_nada_super_slowed.mp3",
            CacheName = "nada_nada_super_slowed.mp3",
        },
        {
            Name = "MONTAGEM RITMO ASTRAL (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "2:12",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/montagem_ritmo_astral_slowed_reverb.mp3",
            CacheName = "montagem_ritmo_astral_slowed_reverb.mp3",
        },
        {
            Name = "we are gods x no, i'm not human",
            Artist = "Artista no especificado",
            Duration = "2:41",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/we_are_gods_x_no_im_not_human.mp3",
            CacheName = "we_are_gods_x_no_im_not_human.mp3",
        },
        {
            Name = "MONTAGEM CAVALONA FANTÁSTICA x Soldier Boy",
            Artist = "Artista no especificado",
            Duration = "1:53",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/montagem_cavalona_fantastica_soldier_boy.mp3",
            CacheName = "montagem_cavalona_fantastica_soldier_boy.mp3",
        },
        {
            Name = "a Man, a Man, a Man (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "3:41",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/a_man_a_man_a_man_slowed_reverb.mp3",
            CacheName = "a_man_a_man_a_man_slowed_reverb.mp3",
        },
        {
            Name = "Fuera del planeta (remix, slowed)",
            Artist = "Artista no especificado",
            Duration = "4:31",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/fuera_del_planeta_remix_slowed.mp3",
            CacheName = "fuera_del_planeta_remix_slowed.mp3",
        },
        {
            Name = "RIDE OR DIE",
            Artist = "Tokischa, Sevdaliza, Villano Antillano",
            Duration = "2:34",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/tokischa_sevdaliza_villano_antillano_ride_or_die.mp3",
            CacheName = "tokischa_sevdaliza_villano_antillano_ride_or_die.mp3",
        },
        {
            Name = "Backstabber",
            Artist = "Artista no especificado",
            Duration = "3:07",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/backstabber.mp3",
            CacheName = "backstabber.mp3",
        },
        {
            Name = "Me Gustas Tú (Slowed)",
            Artist = "Manu Chao",
            Duration = "4:39",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/manu_chao_me_gustas_tu_slowed.mp3",
            CacheName = "manu_chao_me_gustas_tu_slowed.mp3",
        },
        {
            Name = "Estamos tan enamorados",
            Artist = "Artista no especificado",
            Duration = "3:35",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/estamos_tan_enamorados.mp3",
            CacheName = "estamos_tan_enamorados.mp3",
        },
        {
            Name = "Can I Call You Tonight?",
            Artist = "Dayglow",
            Duration = "5:00",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/dayglow_can_i_call_you_tonight.mp3",
            CacheName = "dayglow_can_i_call_you_tonight.mp3",
        },
        {
            Name = "Good Looking",
            Artist = "Suki Waterhouse",
            Duration = "3:36",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/suki_waterhouse_good_looking.mp3",
            CacheName = "suki_waterhouse_good_looking.mp3",
        },
        {
            Name = "Do I Wanna Know?",
            Artist = "Arctic Monkeys",
            Duration = "4:34",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/arctic_monkeys_do_i_wanna_know.mp3",
            CacheName = "arctic_monkeys_do_i_wanna_know.mp3",
        },
        {
            Name = "Love Story (orchestra, slowed)",
            Artist = "Indila",
            Duration = "6:06",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/indila_love_story_orchestra_slowed.mp3",
            CacheName = "indila_love_story_orchestra_slowed.mp3",
        },
        {
            Name = "bingo bingo baby",
            Artist = "Corbon Amodio",
            Duration = "1:24",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/corbon_amodio_bingo_bingo_baby.mp3",
            CacheName = "corbon_amodio_bingo_bingo_baby.mp3",
        },
        {
            Name = "Prom Queen",
            Artist = "Beach Bunny",
            Duration = "2:12",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/beach_bunny_prom_queen.mp3",
            CacheName = "beach_bunny_prom_queen.mp3",
        },
        {
            Name = "I Love You So",
            Artist = "The Walters",
            Duration = "2:36",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/the_walters_i_love_you_so.mp3",
            CacheName = "the_walters_i_love_you_so.mp3",
        },
        {
            Name = "Me Acostumbré (Slowed)",
            Artist = "Arcángel ft. Bad Bunny",
            Duration = "5:14",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/arcangel_bad_bunny_me_acostumbre_slowed.mp3",
            CacheName = "arcangel_bad_bunny_me_acostumbre_slowed.mp3",
        },
        {
            Name = "Lost Soul x The Lost Soul Down",
            Artist = "Artista no especificado",
            Duration = "2:12",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/lost_soul_x_the_lost_soul_down.mp3",
            CacheName = "lost_soul_x_the_lost_soul_down.mp3",
        },
        {
            Name = "Mala (Slowed + Reverb)",
            Artist = "6ix9ine ft. Anuel AA",
            Duration = "4:55",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/6ix9ine_anuel_aa_mala_slowed_reverb.mp3",
            CacheName = "6ix9ine_anuel_aa_mala_slowed_reverb.mp3",
        },
        {
            Name = "Peligrosa (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "4:34",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/peligrosa_slowed_reverb.mp3",
            CacheName = "peligrosa_slowed_reverb.mp3",
        },
        {
            Name = "El efecto",
            Artist = "Artista no especificado",
            Duration = "3:29",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/el_efecto_goku_vegeta.mp3",
            CacheName = "el_efecto_goku_vegeta.mp3",
        },
        {
            Name = "Push the Feeling On x Hotel Room (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "3:41",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/push_the_feeling_on_hotel_room_slowed_reverb.mp3",
            CacheName = "push_the_feeling_on_hotel_room_slowed_reverb.mp3",
        },
        {
            Name = "Music To Watch Boys To",
            Artist = "Lana Del Rey",
            Duration = "4:55",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/lana_del_rey_music_to_watch_boys_to.mp3",
            CacheName = "lana_del_rey_music_to_watch_boys_to.mp3",
        },
        {
            Name = "Sometimes (Light edit)",
            Artist = "Mattyeux, Princess Chelsea",
            Duration = "3:04",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/mattyeux_princess_chelsea_sometimes_light.mp3",
            CacheName = "mattyeux_princess_chelsea_sometimes_light.mp3",
        },
        {
            Name = "A New Kind of Love (Demo, Extended)",
            Artist = "Frou Frou",
            Duration = "7:18",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/frou_frou_a_new_kind_of_love_demo_extended.mp3",
            CacheName = "frou_frou_a_new_kind_of_love_demo_extended.mp3",
        },
        {
            Name = "Montagem Lunar Diamante",
            Artist = "Artista no especificado",
            Duration = "2:08",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/montagem_lunar_diamante.mp3",
            CacheName = "montagem_lunar_diamante.mp3",
        },
        {
            Name = "BIRDS OF A FEATHER",
            Artist = "Billie Eilish",
            Duration = "3:51",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/billie_eilish_birds_of_a_feather_official.mp3",
            CacheName = "billie_eilish_birds_of_a_feather_official.mp3",
        },
        {
            Name = "AUTOMOTIVO DA ZONA SUL 4 (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "5:03",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/automotivo_da_zona_sul_4_slowed_reverb.mp3",
            CacheName = "automotivo_da_zona_sul_4_slowed_reverb.mp3",
        },
        {
            Name = "Andrea",
            Artist = "Bad Bunny",
            Duration = "6:39",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/bad_bunny_andrea.mp3",
            CacheName = "bad_bunny_andrea.mp3",
        },
        {
            Name = "BOOKER T",
            Artist = "Bad Bunny",
            Duration = "2:53",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/bad_bunny_booker_t.mp3",
            CacheName = "bad_bunny_booker_t.mp3",
        },
        {
            Name = "BAILE INOLVIDABLE",
            Artist = "Bad Bunny",
            Duration = "6:18",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/bad_bunny_baile_inolvidable.mp3",
            CacheName = "bad_bunny_baile_inolvidable.mp3",
        },
        {
            Name = "bandida",
            Artist = "bardero$",
            Duration = "3:43",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/bardero_bandida.mp3",
            CacheName = "bardero_bandida.mp3",
        },
        {
            Name = "Ciudad Gris",
            Artist = "Artista no especificado",
            Duration = "3:28",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/ciudad_gris.mp3",
            CacheName = "ciudad_gris.mp3",
        },
        {
            Name = "Ruinas",
            Artist = "Artista no especificado",
            Duration = "2:30",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/ruinas.mp3",
            CacheName = "ruinas.mp3",
        },
        {
            Name = "DOORS LIGHT FUNK (TikTok Version)",
            Artist = "Gamma Jack",
            Duration = "1:43",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/doors_light_funk_tiktok_version_gamma_jack.mp3",
            CacheName = "doors_light_funk_tiktok_version_gamma_jack.mp3",
        },
        {
            Name = "En Que País (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "4:02",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/en_que_pais_slowed_reverb.mp3",
            CacheName = "en_que_pais_slowed_reverb.mp3",
        },
        {
            Name = "Versatile (Hardstyle Remix)",
            Artist = "L.P. Rhythm",
            Duration = "2:17",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/lp_rhythm_versatile_hardstyle_remix_slowed.mp3",
            CacheName = "lp_rhythm_versatile_hardstyle_remix_slowed.mp3",
        },
        {
            Name = "La Paso Cabron (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "5:56",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/la_paso_cabron_slowed_reverb.mp3",
            CacheName = "la_paso_cabron_slowed_reverb.mp3",
        },
        {
            Name = "Love on Me x Prince of Egypt (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "2:53",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/love_on_me_x_prince_of_egypt_slowed_reverb.mp3",
            CacheName = "love_on_me_x_prince_of_egypt_slowed_reverb.mp3",
        },
        {
            Name = "s4nri0 X FUGUE (Super Slowed)",
            Artist = "MAZKO",
            Duration = "1:48",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/mazko_s4nri0_super_slowed_x_fugue.mp3",
            CacheName = "mazko_s4nri0_super_slowed_x_fugue.mp3",
        },
        {
            Name = "MEGA DA TIGER",
            Artist = "DJ ERIK JP, DJ DÉDDA, MC Brunin JP, MC TITI",
            Duration = "2:33",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/mega_da_tiger_dj_erik_jp_dj_dedda_mc_brunin_jp_mc_titi.mp3",
            CacheName = "mega_da_tiger_dj_erik_jp_dj_dedda_mc_brunin_jp_mc_titi.mp3",
        },
        {
            Name = "My Marmalade (Edit Audio)",
            Artist = "Katya Lel",
            Duration = "1:44",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/my_marmalade_katya_lel_edit_audio.mp3",
            CacheName = "my_marmalade_katya_lel_edit_audio.mp3",
        },
        {
            Name = "FENOMENAL (Super Slowed)",
            Artist = "Nakama, KETSU, Mc Staff",
            Duration = "1:16",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/nakama_ketsu_mc_staff_fenomenal_super_slowed.mp3",
            CacheName = "nakama_ketsu_mc_staff_fenomenal_super_slowed.mp3",
        },
        {
            Name = "Me Ama Me Odia (AMV)",
            Artist = "OZUNA, Arcángel, Cosculluela, Brytiago",
            Duration = "6:06",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/me_ama_me_odia_ozuna_arcangel_cosculluela_brytiago.mp3",
            CacheName = "me_ama_me_odia_ozuna_arcangel_cosculluela_brytiago.mp3",
        },
        {
            Name = "TAVI TAVI (Slowed)",
            Artist = "Artista no especificado",
            Duration = "1:41",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/tavi_tavi_slowed.mp3",
            CacheName = "tavi_tavi_slowed.mp3",
        },
        {
            Name = "Your Next Opponent Is You (HardTekk Remix)",
            Artist = "Artista no especificado",
            Duration = "1:38",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/your_next_opponent_is_you_slowed_hardtekk_remix.mp3",
            CacheName = "your_next_opponent_is_you_slowed_hardtekk_remix.mp3",
        },
        {
            Name = "its like im not even here",
            Artist = "mthu",
            Duration = "1:38",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/its_like_im_not_even_here_mthu.mp3",
            CacheName = "its_like_im_not_even_here_mthu.mp3",
        },
        {
            Name = "bevlynous (Slowed Bass)",
            Artist = "bevlynous",
            Duration = "3:35",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/bevlynous_slowed_bass_toji_edit.mp3",
            CacheName = "bevlynous_slowed_bass_toji_edit.mp3",
        },
        {
            Name = "perfect face (Super Slowed)",
            Artist = "laydownrot, mighty eagle",
            Duration = "2:11",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/laydownrot_perfect_face_super_slowed_mighty_eagle.mp3",
            CacheName = "laydownrot_perfect_face_super_slowed_mighty_eagle.mp3",
        },
        {
            Name = "poster boy. (Slowed + Reverb)",
            Artist = "Artista no especificado",
            Duration = "2:39",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/poster_boy_slowed_reverb.mp3",
            CacheName = "poster_boy_slowed_reverb.mp3",
        },
        {
            Name = "Ela Kè Leitada (Slowed)",
            Artist = "Nifour",
            Duration = "2:56",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/ela_ke_leitada_slowed_prod_nifour.mp3",
            CacheName = "ela_ke_leitada_slowed_prod_nifour.mp3",
        },
        {
            Name = "Imitadora (Slowed + Reverb)",
            Artist = "Romeo Santos",
            Duration = "5:39",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/romeo_santos_imitadora_slowed_reverb.mp3",
            CacheName = "romeo_santos_imitadora_slowed_reverb.mp3",
        },
        {
            Name = "MONTAGEM FEATHER (Super Slowed)",
            Artist = "DJ FR3STING, MAHORAGA",
            Duration = "1:31",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/montagem_feather_dj_fr3sting_super_slowed_x_mahoraga.mp3",
            CacheName = "montagem_feather_dj_fr3sting_super_slowed_x_mahoraga.mp3",
        },
        {
            Name = "UNSLEPT FUNK (Slowed + Reverb)",
            Artist = "Yuji Itadori",
            Duration = "1:46",
            Cover = "",
            AudioURL = "https://raw.githubusercontent.com/nbritez672-tech/Yin-controllermusic/main/unslept_funk_slowed_reverb_yuji_itadori.mp3",
            CacheName = "unslept_funk_slowed_reverb_yuji_itadori.mp3",
        },
    },
}
